#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.2.4f1_c63b2af89a85"
#define UNITY_VERSION_FULL_NICE "2019.2.4f1 (c63b2af89a85)"
#define UNITY_VERSION_BLD 12991274
#define UNITY_VERSION_DATE 1566945370
#define UNITY_VERSION_WIN "2019.2.4.12991274"
#define UNITY_VERSION_BRANCH "2019.2/staging"
