#pragma once
// Generated by build script, do not edit!
#define UNITY_COMPANY "Unity Technologies ApS"
#define UNITY_COPYRIGHT "(c) 2019 Unity Technologies ApS. All rights reserved."
#define UNITY_ENABLE_HWSTATS_REPORT 1
#define UNITY_BUILD_ROOT "C:/buildslave/unity/build"
